fix(stow): when try to stow into an already existing config file the default behaviour, now, will be to override the current config
Signed-off-by: Daniel Boll <danielboll.academico@gmail.com>

diff --git a/install b/install
--- a/install
+++ b/install
@@ -6,6 +6,12 @@ echo $DOTFILES
 for folder in $(sed 's/,/ /g'<<<$STOW_FOLDERS)
 do
     stow --restow $folder
+
+    # If the folder already exists --restow will fail.
+    # In that case, we need to stow with the --adopt flag which will overwrite the existing files.
+    if [ $? -ne 0 ]; then
+        stow --adopt $folder
+    fi
 done
 
 post-install
